[package]
name = "re1doorskip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.dependencies]

[target.'cfg(unix)'.dependencies]
procfs = "0.13.0"
